# Generated by Django 3.1.5 on 2021-02-11 02:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cta_x_cbr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago_cta_x_cobrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cta_cobrar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cta_x_cbr.cta_x_cobrar')),
            ],
            options={
                'verbose_name': 'pago_ctas_cobrar',
                'db_table': 'pago_ctas_cobrar',
            },
        ),
    ]
