# Generated by Django 3.1.5 on 2021-02-12 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago_cta_x_cbr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago_cta_x_cobrar',
            name='estado',
            field=models.IntegerField(choices=[(0, 'POR VENCER'), (1, 'VENCIDA'), (2, 'PAGADA')], default=0),
        ),
        migrations.AddField(
            model_name='pago_cta_x_cobrar',
            name='fecha_pago',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
