# Generated by Django 3.1.5 on 2021-02-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago_cta_x_cbr', '0003_auto_20210212_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago_cta_x_cobrar',
            name='fecha_pago',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
