# Generated by Django 3.1.5 on 2021-02-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago_cta_x_cbr', '0004_auto_20210212_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago_cta_x_cobrar',
            name='valor_pagado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
