# Generated by Django 3.1.5 on 2021-02-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago_cta_x_cbr', '0005_pago_cta_x_cobrar_valor_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago_cta_x_cobrar',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
