# Generated by Django 3.1.5 on 2021-02-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cta_x_cbr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cta_x_cobrar',
            name='nro_cuotas',
            field=models.IntegerField(default=1),
        ),
    ]
