# Generated by Django 3.1.5 on 2021-02-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cta_x_cbr', '0003_cta_x_cobrar_interes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cta_x_cobrar',
            name='tolal_deuda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
