# Generated by Django 3.1.5 on 2021-06-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioweb', '0002_remove_sitioweb_mapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitioweb',
            name='acerca',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitioweb',
            name='coordenadas',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
