# Generated by Django 3.1.5 on 2021-05-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_compra_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='user',
        ),
    ]
