# Generated by Django 3.1.5 on 2021-05-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_auto_20210508_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tipo_pago',
            field=models.IntegerField(choices=[(0, 'CONTADO'), (1, 'CREDITO'), (2, 'NO ACREDITADO')], default=0),
        ),
    ]
