# Generated by Django 3.1.5 on 2021-05-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DatabaseBackups', '0003_databasebackups_fecha'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='databasebackups',
            table='respaldo_datos',
        ),
    ]
