# Generated by Django 3.1.5 on 2021-02-06 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categoria.categoria')),
            ],
            options={
                'verbose_name': 'producto_base',
                'verbose_name_plural': 'productos_base',
                'db_table': 'producto_base',
                'ordering': ['-id', '-nombre', '-categoria'],
            },
        ),
    ]
