# Generated by Django 3.1.5 on 2021-05-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_base',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
