# Generated by Django 3.1.5 on 2021-05-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatabaseBackups',
        ),
    ]
