# Generated by Django 3.1.5 on 2021-01-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20210114_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='indice',
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
    ]
